[unstable]
profile-rustflags = true

[profile.opt-bench]
opt-level = 3
debug = false
rustflags = ["-C", "no-prepopulate-passes", "-Z", "mir-opt-level=3", "-C", "embed-bitcode"]
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false
inherits = "release"
