name: Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: baseline
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git -C llvm/llvm-project checkout .
          git -C llvm/llvm-project clean -fdx

      - name: Build LLVM with coverage instrumentation
        run: ${{ github.workspace }}/scripts/build_cov.sh

