name: Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: baseline
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git -C llvm/llvm-project checkout .
          git -C llvm/llvm-project clean -fdx
          git -C llvm/llvm-project apply ../llvm-cov.diff

      - name: Build LLVM with coverage instrumentation
        run: ${{ github.workspace }}/scripts/build_cov.sh

      - name: Run opt
        run: python3 ${{ github.workspace }}/scripts/gen_optimized_cov.py bench ${{ github.workspace }}/llvm/llvm-cov-build/bin/opt

      - name: Collect coverage data
        working-directory: ${{ github.workspace }}/llvm/llvm-cov-build
        run: cmake --build . --target generate-coverage-report

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/llvm/llvm-cov-build/report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
