name: DAG grep

on:
  issues:
    types: labeled

jobs:
  build:
    if: github.event.label.name == 'grep'
    runs-on: [self-hosted, grep]

    permissions:
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          ref: main

      - name: Set up Git
        run: ${{ github.workspace }}/scripts/setup_git.sh

      - name: Get Pattern IR
        run: |
          echo "${TEXT}" | sed -n '/^```/,/^```/ p' | sed '/^```/ d' > ${{ github.workspace }}/test.ll
          cat ${{ github.workspace }}/test.ll
        env:
          TEXT: ${{ github.event.issue.body }}

      - name: Run LLVM DAG Grep
        run: |
          ${{ github.workspace }}/scripts/run_dag_grep.sh
          cat ${{ github.workspace }}/scripts/grep.md

      - name: Report
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: scripts/grep.md
