name: CI

on:
  schedule:
  - cron: "0 */1 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, baseline]

    permissions:
      issues: write
      contents: write

    concurrency:
      group: baseline
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          ref: main

      - name: Set up Git
        run: ${{ github.workspace }}/scripts/setup_git.sh

      - name: Update LLVM
        run: ${{ github.workspace }}/scripts/update_llvm.sh

      - name: Update optimized IR
        id: update
        run: |
          ${{ github.workspace }}/scripts/update_optimized.sh
          cat ${{ github.workspace }}/scripts/issue.md

      - name: Report
        uses: JasonEtco/create-an-issue@v2
        if: steps.update.outputs.SHOULD_OPEN_ISSUE == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: scripts/issue.md
